package entities;

public enum DiningHallTypes {
    NEW_COLLEGE_DINING_HALL,
    UNIVERSITY_COLLEGE_DINING_HALL,
    ST_MICHAELS_COLLEGE_DINING_HALL,
    VICTORIA_COLLEGE_DINING_HALL,
    TRINITY_COLLEGE_DINING_HALL,
    WOODSWORTH_COLLEGE_DINING_HALL,
    INNIS_COLLEGE_DINING_HALL,
    CHESTNUT_DINING_HALL,
    CAMPUS_ONE_DINING_HALL
}
