package entities;

public enum ResidenceTypes {
    NEW_COLLEGE,
    UNIVERSITY_COLLEGE,
    ST_MICHAELS_COLLEGE,
    VICTORIA_COLLEGE,
    TRINITY_COLLEGE,
    WOODSWORTH_COLLEGE,
    INNIS_COLLEGE,
    CHESTNUT,
    CAMPUS_ONE
}
